config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
    resources :topics
  end

  resources :topics do

    member do
      put :fav
      put :unfav
    end

    resources :comments do
      member do
        put :flag
        put :unflag
      end
    end

  end

  get 'about' => 'static_page#about'
  root to: "topics#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many   :flags
  has_many   :flaggers, through: :flag, source: :user

  validates :user, :body, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many   :comments
  has_many   :favorites
  has_many   :favoriters, through: :favorites, source: :user

  validates :body, :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :flags
  has_many :flagged_comments, through: :flags, source: :comment
  has_many :topics
  has_many :comments
  has_many :favorites
  has_many :favorited_topics, through: :favorites, source: :topic

  validates :email, presence: true, uniqueness: true

# FLAG

  def already_flagged?(comment)
    flagged_comments.find_by_id(comment.id)
  end

  def flag_comment!(comment)
    return if flagged_comments.find_by_id(comment.id)
    flagged_comments << comment
  end

  def unflag_comment!(comment)
    return unless flagged_comments.find_by_id(comment.id)
    flagged_comments.delete(comment)
  end

# FAVORITE

  def already_favorited?(topic)
    favorited_topics.find_by_id(topic.id)
  end

  def fav_topic!(topic)
    return if favorited_topics.find_by_id(topic.id)
    favorited_topics << topic
  end

  def unfav_topic!(topic)
    return unless favorited_topics.find_by_id(topic.id)
    favorited_topics.delete(topic)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin

  protected

  def verify_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController

  before_action :set_topic, only: [:show, :edit, :update, :destroy]


  def index
    @topics = Topic.all
  end

  def show; end

  def new
    @topic = current_user.topics.build
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, notice: "Topic created master!"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  protected

    def topic_params
      params.require(:topic).permit(:body, :title)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

def index
  @users = User.all
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :get_current_topic
  before_action :get_current_comment, only: [:flag, :unflag]

  def create
    @comment          = current_user.comments.new(comment_params)
    @comment.topic_id = @topic.id
    @comment.save
    redirect_to topic_path(@topic)
  end

  def new
    @comment = current_user.comments.new
  end

  def flag
    current_user.flag_comment!(@comment)
    redirect_to topic_path(@topic), notice: "Comment Flagged as inappropriate"
  end

  def unflag
    current_user.unflag_comment!(@comment)
    redirect_to topic_path(@topic), notice: "Comment Unflagged"
  end

private

def get_current_comment
  @comment = Comment.find(params[:id])
end

def get_current_topic
    @topic = Topic.find(params[:topic_id])
end

def comment_params
  params.require(:comment).permit(:body)
end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def about
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


  before_action :authenticate_user!, except: [:show, :index]
  before_action :get_current_topic, only: [:show, :fav, :unfav]

  def index
    @topics = Topic.all
  end

  def show
    @comment = @topic.comments.new
  end

  def fav
    current_user.fav_topic!(@topic)
    redirect_to topic_path(@topic), notice: "Topic is now favorite"
  end

  def unfav
    current_user.unfav_topic!(@topic)
    redirect_to topic_path(@topic), notice: "Topic is no longer favorite"
  end

  private

  def topic_params
    params.require(:topic).permit(:body, :title)
  end

  def get_current_topic
    @topic = Topic.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/topics/_form.html.erb
<%= form_for [:admin, topic] do |f| %>

<div class"field">
  <%= f.label      :title %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label     :body %>
  <%= f.text_area :body %>
</div>

<div class="action">
  <%= f.submit %>
  <span>or</span>
  <%= link_to "Cancel", root_path %>
</div>
<% end -%>

app/views/admin/topics/edit.html.erb
<h2>Edit topic</h2>

<%= render partial: "admin/topics/form", locals: { topic: @topic } %>

app/views/admin/topics/index.html.erb
<%= link_to "New Topic", new_admin_topic_path, class: "btn btn-default" %><br><br>

<table class="table table-striped">
  <td > <strong>TITLE</strong> </td>
  <td > <strong>BODY</strong></td>
  <td > <strong>EDIT</strong> </td>
  <td > <strong>DELETE</strong> </td>
  <% @topics.each do |topic| %>
    <tr>
      <td><strong><%= link_to "#{topic.title}", topic_path(topic) %></strong></td>
      <td><%= topic.body %></td>
      <td><%= link_to "Edit", edit_admin_topic_path(topic), class: "btn btn-xs btn-primary" %></td>
      <td> <%= link_to "Destroy", admin_topic_path(topic), method: :delete, class: "btn btn-xs btn-primary" %></td>
    </tr>
  <% end -%>
</table>

app/views/admin/topics/new.html.erb
<h2>New Topic</h2>
<%= render partial: "admin/topics/form", locals: { topic: @topic } %>

app/views/admin/users/index.html.erb
<table class="table table-striped">
  <td><strong>ID</strong></td>
  <td><strong>E-MAIL</strong></td>
  <td><strong>LAST LOG IN</strong></td>
  <td><strong>ADMIN</strong></td>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= time_ago_in_words(user.last_sign_in_at) %></td>
      <td><%= user.admin.to_s.capitalize %></td>
    </tr>
  <% end -%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalInsignia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "TOPICANA", root_path, class: "navbar-brand" %> <p class="navbar-text">your opinion matters</p>
          <%= link_to "About Us", about_path, class: "btn btn-default navbar-btn pull-right"%>
        </div>
          <% if current_user %>
            <p class="navbar-text navbar-right">Logged in as <strong> <%= current_user.email %> </strong></p>
            <%= link_to "Log out",    destroy_user_session_path, method: :delete, class: "btn btn-danger navbar-btn pull-right" %>
             <% if current_user.admin? %>
               <%= link_to "Topics", admin_topics_path, class: "btn btn-primary navbar-btn pull-right" %>
               <%= link_to "Users", admin_users_path, class: "btn btn-primary navbar-btn pull-right" %>
            <% end -%>
            <% else %>
              <%= link_to "Sign up",     new_user_registration_path, class: "btn btn-success navbar-btn pull-right" %>
              <%= link_to "Log In", user_session_path, class: "btn btn-success navbar-btn pull-right" %>
            <% end -%>
      </div>
    </nav>
    <p class="notice alert-success"><%= notice %></p>
    <p class="alert" ><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_page/about.html.erb
<div class="well">
  <h1>Welcome!</h1>
  <p>We are a community of people concerned about diverse topics.</p>
  <p>Your opinion matters to us...</p>
  <p>That's why we want to hear what you have to say about them.</p>
  <p>Thank you, and enjoy your stay!</p>
</div>

app/views/topics/_comments.html.erb
<% comments.each do |comment| %>
  <% unless comment.new_record? %>
    <div class="list-group comments">
      <div class="list-group-item">
        <p><%= comment.user.email %> said:</p>
        <p><%= comment.body %></p>
        <p class="comment-detail"><%= time_ago_in_words(comment.created_at) %> ago</p>
          <% if current_user && current_user.already_flagged?(comment) %>
            <%= link_to "Unflag", unflag_topic_comment_path(topic, comment), method: :put, class: "btn btn-warning btn-xs" %>
          <% else %>
            <%= link_to "Flag",   flag_topic_comment_path(topic, comment), method: :put, class: "btn btn-danger btn-xs" %>
          <% end -%>
        <br>
      </div>
    </div>
  <% end -%>
<% end -%>

app/views/topics/_form.html.erb
<hr>
<%= form_for @comment, url: topic_comments_path(@topic) do |f| %>

  <div>
  <%= f.label "Write your opinion" %> <br>
  <%= f.text_area :body %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end -%>
<br>

app/views/topics/index.html.erb
<h2>Current Topics</h2>
    <% @topics.each do |topic| %>
      <div class="col-xs-12 col-md-4 list group well">
      <h4 class="list-group-item-heading "><%= link_to topic.title, topic_path(topic), class: "list-group-item active" %></h4>
      <p class="list-group-item-text lead"> <%= topic.body %> </p>
      </div>
    <% end -%>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>

<class class="field">
  <%= f.label      :title %>
  <%= f.text_field :title %>
</class>

<div class="field">
  <%= f.label     :body %>
  <%= f.text_area :body %>
</div>

<div class="action">
  <%= f.submit %>
  <span>or</span>
  <%= link_to "Cancel", root_path %>
</div>


<% end -%>

app/views/topics/show.html.erb
<div class="row">
  <div class="col col-md-6">
  <h2><%= @topic.title %></h2>
    <p><%= @topic.body %></p>
      <% if current_user && current_user.already_favorited?(@topic) %>
        <%= link_to "Un-Favorite this topic", unfav_topic_path(@topic), method: :put, class: "btn btn-warning btn-sm" %>
      <% else %>
        <%= link_to "Favorite this topic", fav_topic_path(@topic),   method: :put, class: "btn btn-success btn-sm" %></h2>
      <% end -%>
  </div>
  <div class="col col-md-6">
  <h3> Comments </h3>
   <% if @topic.comments.any? %>
      <div class="commentsList">
        <%= render partial: 'topics/comments', locals: { topic: @topic, comments: @topic.comments } %>
      </div>
    <% end -%>
  <div >
    <%= render partial: 'topics/form', locals: { topic: @topic, comments: @topic.comments } %>
   </div>
  </div>
</div>